In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import sklearn.linear_model as lm_model
from sklearn import metrics
from sklearn.model_selection  import train_test_split
from sklearn.model_selection  import cross_val_score
from sklearn.model_selection  import KFold
from sklearn.preprocessing import PolynomialFeatures

In [2]:
# Read Dataset
House_Sale = pd.read_csv("..../ASS05_Data.csv")

In [3]:
#View Dataset
House_Sale

      LotArea  TotalBsmtSF  GarageCars  SalePrice  AGE  TotalArea
0       12108         1440           0     118000   53       1440
1        9400          945           0     127500   31        980
2        1680          672           0      91500   35       1218
3        8430         1040           0     124000   31       1040
4        7500         1080           0     141000    4       1080
...       ...          ...         ...        ...  ...        ...
1455     8100          849           2     106000  111       2138
1456     9142         1020           1     137000   96       1928
1457    45600          907           2     240000  100       2358
1458    10320          756           1     135000  102       1469
1459     7200         1214           2     133900   97       2291

[1460 rows x 6 columns]

In [4]:
House_Sale.shape  # Number of rows and columns

(1460, 6)

In [5]:
House_Sale.info() # Describe column names and its types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 6 columns):
LotArea        1460 non-null int64
TotalBsmtSF    1460 non-null int64
GarageCars     1460 non-null int64
SalePrice      1460 non-null int64
AGE            1460 non-null int64
TotalArea      1460 non-null int64
dtypes: int64(6)
memory usage: 68.6 KB

In [6]:
House_Sale.describe()

,LotArea,TotalBsmtSF,GarageCars,SalePrice,AGE,TotalArea
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,10516.828082,1057.429452,1.767123,180921.195890,36.547945,1509.619178
std,9981.264932,438.705324,0.747315,79442.502883,30.250152,521.163523
min,1300.000000,0.000000,0.000000,34900.000000,0.000000,334.000000
25%,7553.500000,795.750000,1.000000,129975.000000,8.000000,1123.750000
50%,9478.500000,991.500000,2.000000,163000.000000,35.000000,1458.000000
75%,11601.500000,1298.250000,2.000000,214000.000000,54.000000,1775.250000
max,215245.000000,6110.000000,4.000000,755000.000000,136.000000,5642.000000

In [7]:
House_Sale = House_Sale[['LotArea', 'TotalBsmtSF', 'GarageCars', 'AGE', 'TotalArea', 'SalePrice']]

In [8]:
House_Sale.columns = [['LotArea', 'TotalBsmtSF', 'GarageCars', 'AGE', 'TotalArea', 'TrueTarget']]

In [9]:
House_Sale

     LotArea TotalBsmtSF GarageCars  AGE TotalArea TrueTarget
0      12108        1440          0   53      1440     118000
1       9400         945          0   31       980     127500
2       1680         672          0   35      1218      91500
3       8430        1040          0   31      1040     124000
4       7500        1080          0    4      1080     141000
...      ...         ...        ...  ...       ...        ...
1455    8100         849          2  111      2138     106000
1456    9142        1020          1   96      1928     137000
1457   45600         907          2  100      2358     240000
1458   10320         756          1  102      1469     135000
1459    7200        1214          2   97      2291     133900

[1460 rows x 6 columns]

# Modelling Assignmnet Part I: The Validation Set Approach

In [10]:
# Split data in 70% as Train and 30% as Test
train_House_Sale = House_Sale.sample(1022, random_state = 1)
test_House_Sale = House_Sale[~House_Sale.isin(train_House_Sale)].dropna(how = 'all')

#Divide train and test data in X and Y to build model
X_train_House_Sale = pd.DataFrame(train_House_Sale.iloc[:,:-1])
y_train_House_Sale = pd.DataFrame(train_House_Sale.iloc[:,-1])
X_test_House_Sale = pd.DataFrame(test_House_Sale.iloc[:,:-1])
y_test_House_Sale = pd.DataFrame(test_House_Sale.iloc[:,-1])

print("Split I")
print()

# Linear Regression Model on Data Spilt I
Linear_model = sm.OLS(y_train_House_Sale, X_train_House_Sale).fit()
print(Linear_model.summary())
print()
print()

print("Accuracy of Model = ", Linear_model.rsquared * 100)
print()

print("MSE of Training Model = ", metrics.mean_squared_error(y_train_House_Sale,Linear_model.predict(X_train_House_Sale)))
print("ASE of Validation Set = ", metrics.mean_squared_error(y_test_House_Sale, Linear_model.predict(X_test_House_Sale)))
print()

LinearReg = lm_model.LinearRegression()

# Quadratic Model on Data Spilt I
poly = PolynomialFeatures(degree=2)
X_train_House_Sale2 = poly.fit_transform(X_train_House_Sale)
X_test_House_Sale2 = poly.fit_transform(X_test_House_Sale)
Quadratic_model = LinearReg.fit(X_train_House_Sale2, y_train_House_Sale)
print("MSE of Quadratic Model = ", metrics.mean_squared_error(y_test_House_Sale, Quadratic_model.predict(X_test_House_Sale2)))

# Cubic Model on Data Spilt I
poly = PolynomialFeatures(degree=3)
X_train_House_Sale3 = poly.fit_transform(X_train_House_Sale)
X_test_House_Sale3 = poly.fit_transform(X_test_House_Sale)
Cubic_model = LinearReg.fit(X_train_House_Sale3, y_train_House_Sale)
print("MSE of Cubic Model = ", metrics.mean_squared_error(y_test_House_Sale, Cubic_model.predict(X_test_House_Sale3)))

Split I

                                 OLS Regression Results
=======================================================================================
Dep. Variable:             TrueTarget   R-squared (uncentered):                   0.964
Model:                            OLS   Adj. R-squared (uncentered):              0.964
Method:                 Least Squares   F-statistic:                              5518.
Date:                Wed, 11 Mar 2020   Prob (F-statistic):                        0.00
Time:                        08:44:30   Log-Likelihood:                         -12199.
No. Observations:                1022   AIC:                                  2.441e+04
Df Residuals:                    1017   BIC:                                  2.443e+04
Df Model:                           5
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
LotArea         0.5987      0.121      4.960      0.000       0.362       0.836
TotalBsmtSF    51.9951      2.998     17.344      0.000      46.112      57.878
GarageCars   1.524e+04   1887.617      8.074      0.000    1.15e+04    1.89e+04
AGE          -593.0810     35.085    -16.904      0.000    -661.928    -524.234
TotalArea      76.8094      2.661     28.863      0.000      71.587      82.031
==============================================================================
Omnibus:                      302.886   Durbin-Watson:                   2.080
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2447.201
Skew:                           1.126   Prob(JB):                         0.00
Kurtosis:                      10.239   Cond. No.                     2.37e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.37e+04. This might indicate that there are
strong multicollinearity or other numerical problems.


Accuracy of Model =  96.4446166122947

MSE of Training Model =  1366886652.6120195
ASE of Validation Set =  2882910522.722032

MSE of Quadratic Model =  5065348924.606426
MSE of Cubic Model =  15233202697.940378

In [11]:
# Split data in 70% as Train and 30% as Test
train_House_Sale = House_Sale.sample(1022, random_state = 2)
test_House_Sale = House_Sale[~House_Sale.isin(train_House_Sale)].dropna(how = 'all')

#Divide train and test data in X and Y to build model
X_train_House_Sale = pd.DataFrame(train_House_Sale.iloc[:,:-1])
y_train_House_Sale = pd.DataFrame(train_House_Sale.iloc[:,-1])
iX_test_House_Sale = pd.DataFrame(test_House_Sale.iloc[:,:-1])
y_test_House_Sale = pd.DataFrame(test_House_Sale.iloc[:,-1])

print("Split II")
print()

# Linear Regression Model on Data Spilt II
Linear_model = sm.OLS(y_train_House_Sale, X_train_House_Sale).fit()
print(Linear_model.summary())
print()
print()

print("Accuracy of Model = ", Linear_model.rsquared * 100)
print()

print("MSE of Training Model = ", metrics.mean_squared_error(y_train_House_Sale,Linear_model.predict(X_train_House_Sale)))
print("ASE of Validation Set = ", metrics.mean_squared_error(y_test_House_Sale, Linear_model.predict(X_test_House_Sale)))
print()

LinearReg = lm_model.LinearRegression()

# Quadratic Model on Data Spilt II
poly = PolynomialFeatures(degree=2)
X_train_House_Sale2 = poly.fit_transform(X_train_House_Sale)
X_test_House_Sale2 = poly.fit_transform(X_test_House_Sale)
Quadratic_model = LinearReg.fit(X_train_House_Sale2, y_train_House_Sale)
print("MSE of Quadratic Model = ", metrics.mean_squared_error(y_test_House_Sale, Quadratic_model.predict(X_test_House_Sale2)))

# Cubic Model on Data Spilt II
poly = PolynomialFeatures(degree=3)
X_train_House_Sale3 = poly.fit_transform(X_train_House_Sale)
X_test_House_Sale3 = poly.fit_transform(X_test_House_Sale)
Cubic_model = LinearReg.fit(X_train_House_Sale3, y_train_House_Sale)
print("MSE of Cubic Model = ", metrics.mean_squared_error(y_test_House_Sale, Cubic_model.predict(X_test_House_Sale3)))

Split II

                                 OLS Regression Results
=======================================================================================
Dep. Variable:             TrueTarget   R-squared (uncentered):                   0.960
Model:                            OLS   Adj. R-squared (uncentered):              0.960
Method:                 Least Squares   F-statistic:                              4886.
Date:                Wed, 11 Mar 2020   Prob (F-statistic):                        0.00
Time:                        08:44:34   Log-Likelihood:                         -12273.
No. Observations:                1022   AIC:                                  2.456e+04
Df Residuals:                    1017   BIC:                                  2.458e+04
Df Model:                           5
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
LotArea         0.4590      0.138      3.321      0.001       0.188       0.730
TotalBsmtSF    52.7910      3.246     16.262      0.000      46.421      59.161
GarageCars   1.625e+04   2004.150      8.107      0.000    1.23e+04    2.02e+04
AGE          -573.5127     37.806    -15.170      0.000    -647.700    -499.325
TotalArea      74.2748      2.870     25.877      0.000      68.642      79.907
==============================================================================
Omnibus:                      235.031   Durbin-Watson:                   1.961
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9683.841
Skew:                           0.002   Prob(JB):                         0.00
Kurtosis:                      18.080   Cond. No.                     2.29e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.29e+04. This might indicate that there are
strong multicollinearity or other numerical problems.


Accuracy of Model =  96.00322470520149

MSE of Training Model =  1577491908.0313451
ASE of Validation Set =  2336527556.7776713

MSE of Quadratic Model =  1728266429.6313064
MSE of Cubic Model =  248751749823.2115

In [12]:
# Split data in 70% as Train and 30% as Test
train_House_Sale = House_Sale.sample(1022, random_state = 3)
test_House_Sale = House_Sale[~House_Sale.isin(train_House_Sale)].dropna(how = 'all')

#Divide train and test data in X and Y to build model
X_train_House_Sale = pd.DataFrame(train_House_Sale.iloc[:,:-1])
y_train_House_Sale = pd.DataFrame(train_House_Sale.iloc[:,-1])
X_test_House_Sale = pd.DataFrame(test_House_Sale.iloc[:,:-1])
y_test_House_Sale = pd.DataFrame(test_House_Sale.iloc[:,-1])

print("Split III")
print()

# Linear Regression Model on Data Spilt III
Linear_model = sm.OLS(y_train_House_Sale, X_train_House_Sale).fit()
print(Linear_model.summary())
print()
print()

print("Accuracy of Model = ", Linear_model.rsquared * 100)
print()

print("MSE of Training Model = ", metrics.mean_squared_error(y_train_House_Sale,Linear_model.predict(X_train_House_Sale)))
print("ASE of Validation Set = ", metrics.mean_squared_error(y_test_House_Sale, Linear_model.predict(X_test_House_Sale)))
print()

LinearReg = lm_model.LinearRegression()

# Quadratic Model on Data Spilt III
poly = PolynomialFeatures(degree=2)
X_train_House_Sale2 = poly.fit_transform(X_train_House_Sale)
X_test_House_Sale2 = poly.fit_transform(X_test_House_Sale)
Quadratic_model = LinearReg.fit(X_train_House_Sale2, y_train_House_Sale)
print("MSE of Quadratic Model = ", metrics.mean_squared_error(y_test_House_Sale, Quadratic_model.predict(X_test_House_Sale2)))

# Cubic Model on Data Spilt III
poly = PolynomialFeatures(degree=3)
X_train_House_Sale3 = poly.fit_transform(X_train_House_Sale)
X_test_House_Sale3 = poly.fit_transform(X_test_House_Sale)
Cubic_model = LinearReg.fit(X_train_House_Sale3, y_train_House_Sale)
print("MSE of Cubic Model = ", metrics.mean_squared_error(y_test_House_Sale, Cubic_model.predict(X_test_House_Sale3)))

Split III

                                 OLS Regression Results
=======================================================================================
Dep. Variable:             TrueTarget   R-squared (uncentered):                   0.953
Model:                            OLS   Adj. R-squared (uncentered):              0.953
Method:                 Least Squares   F-statistic:                              4140.
Date:                Wed, 11 Mar 2020   Prob (F-statistic):                        0.00
Time:                        08:44:38   Log-Likelihood:                         -12331.
No. Observations:                1022   AIC:                                  2.467e+04
Df Residuals:                    1017   BIC:                                  2.470e+04
Df Model:                           5
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
LotArea         0.2496      0.150      1.660      0.097      -0.046       0.545
TotalBsmtSF    42.5098      3.401     12.497      0.000      35.835      49.185
GarageCars   2.733e+04   2069.452     13.207      0.000    2.33e+04    3.14e+04
AGE          -456.3578     39.690    -11.498      0.000    -534.242    -378.473
TotalArea      65.4365      3.115     21.010      0.000      59.325      71.548
==============================================================================
Omnibus:                      597.749   Durbin-Watson:                   2.014
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            51214.434
Skew:                          -1.801   Prob(JB):                         0.00
Kurtosis:                      37.492   Cond. No.                     2.22e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.22e+04. This might indicate that there are
strong multicollinearity or other numerical problems.


Accuracy of Model =  95.3170428657588

MSE of Training Model =  1769557210.2508607
ASE of Validation Set =  1853631301.073397

MSE of Quadratic Model =  1621915335.9660006
MSE of Cubic Model =  9331442709.695105

In [13]:
# Split data in 70% as Train and 30% as Test
train_House_Sale = House_Sale.sample(1022, random_state = 4)
test_House_Sale = House_Sale[~House_Sale.isin(train_House_Sale)].dropna(how = 'all')

#Divide train and test data in X and Y to build model
X_train_House_Sale = pd.DataFrame(train_House_Sale.iloc[:,:-1])
y_train_House_Sale = pd.DataFrame(train_House_Sale.iloc[:,-1])
X_test_House_Sale = pd.DataFrame(test_House_Sale.iloc[:,:-1])
y_test_House_Sale = pd.DataFrame(test_House_Sale.iloc[:,-1])

print("Split IV")
print()

# Linear Regression Model on Data Spilt IV
Linear_model = sm.OLS(y_train_House_Sale, X_train_House_Sale).fit()
print(Linear_model.summary())
print()
print()

print("Accuracy of Model = ", Linear_model.rsquared * 100)
print()

print("MSE of Training Model = ", metrics.mean_squared_error(y_train_House_Sale,Linear_model.predict(X_train_House_Sale)))
print("ASE of Validation Set = ", metrics.mean_squared_error(y_test_House_Sale, Linear_model.predict(X_test_House_Sale)))
print()

LinearReg = lm_model.LinearRegression()

# Quadratic Model on Data Spilt IV
poly = PolynomialFeatures(degree=2)
X_train_House_Sale2 = poly.fit_transform(X_train_House_Sale)
X_test_House_Sale2 = poly.fit_transform(X_test_House_Sale)
Quadratic_model = LinearReg.fit(X_train_House_Sale2, y_train_House_Sale)
print("MSE of Quadratic Model = ", metrics.mean_squared_error(y_test_House_Sale, Quadratic_model.predict(X_test_House_Sale2)))

# Cubic Model on Data Spilt IV
poly = PolynomialFeatures(degree=3)
X_train_House_Sale3 = poly.fit_transform(X_train_House_Sale)
X_test_House_Sale3 = poly.fit_transform(X_test_House_Sale)
Cubic_model = LinearReg.fit(X_train_House_Sale3, y_train_House_Sale)
print("MSE of Cubic Model = ", metrics.mean_squared_error(y_test_House_Sale, Cubic_model.predict(X_test_House_Sale3)))

Split IV

                                 OLS Regression Results
=======================================================================================
Dep. Variable:             TrueTarget   R-squared (uncentered):                   0.951
Model:                            OLS   Adj. R-squared (uncentered):              0.951
Method:                 Least Squares   F-statistic:                              3944.
Date:                Wed, 11 Mar 2020   Prob (F-statistic):                        0.00
Time:                        08:44:42   Log-Likelihood:                         -12365.
No. Observations:                1022   AIC:                                  2.474e+04
Df Residuals:                    1017   BIC:                                  2.477e+04
Df Model:                           5
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
LotArea         0.4885      0.140      3.502      0.000       0.215       0.762
TotalBsmtSF    36.5187      3.533     10.337      0.000      29.587      43.451
GarageCars   2.598e+04   2081.986     12.477      0.000    2.19e+04    3.01e+04
AGE          -460.6929     40.222    -11.454      0.000    -539.621    -381.765
TotalArea      70.4441      3.036     23.202      0.000      64.486      76.402
==============================================================================
Omnibus:                      522.398   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            46772.477
Skew:                          -1.418   Prob(JB):                         0.00
Kurtosis:                      36.020   Cond. No.                     2.28e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.28e+04. This might indicate that there are
strong multicollinearity or other numerical problems.


Accuracy of Model =  95.09571464625499

MSE of Training Model =  1890618931.0978496
ASE of Validation Set =  1539064476.029725

MSE of Quadratic Model =  1235027339.5934212
MSE of Cubic Model =  1381523754.900851

In [14]:
# Split data in 70% as Train and 30% as Test
train_House_Sale = House_Sale.sample(1022, random_state = 5)
test_House_Sale = House_Sale[~House_Sale.isin(train_House_Sale)].dropna(how = 'all')

#Divide train and test data in X and Y to build model
X_train_House_Sale = pd.DataFrame(train_House_Sale.iloc[:,:-1])
y_train_House_Sale = pd.DataFrame(train_House_Sale.iloc[:,-1])
X_test_House_Sale = pd.DataFrame(test_House_Sale.iloc[:,:-1])
y_test_House_Sale = pd.DataFrame(test_House_Sale.iloc[:,-1])

print("Split V")
print()

# Linear Regression Model on Data Spilt V
Linear_model = sm.OLS(y_train_House_Sale, X_train_House_Sale).fit()
print(Linear_model.summary())
print()
print()

print("Accuracy of Model = ", Linear_model.rsquared * 100) 
print()

print("MSE of Training Model = ", metrics.mean_squared_error(y_train_House_Sale,Linear_model.predict(X_train_House_Sale)))
print("ASE of Validation Set = ", metrics.mean_squared_error(y_test_House_Sale, Linear_model.predict(X_test_House_Sale)))
print()

LinearReg = lm_model.LinearRegression()

# Quadratic Model on Data Spilt V
poly = PolynomialFeatures(degree=2)
X_train_House_Sale2 = poly.fit_transform(X_train_House_Sale)
X_test_House_Sale2 = poly.fit_transform(X_test_House_Sale)
Quadratic_model = LinearReg.fit(X_train_House_Sale2, y_train_House_Sale)
print("MSE of Quadratic Model = ", metrics.mean_squared_error(y_test_House_Sale, Quadratic_model.predict(X_test_House_Sale2)))

# Cubic Model on Data Spilt V
poly = PolynomialFeatures(degree=3)
X_train_House_Sale3 = poly.fit_transform(X_train_House_Sale)
X_test_House_Sale3 = poly.fit_transform(X_test_House_Sale)
Cubic_model = LinearReg.fit(X_train_House_Sale3, y_train_House_Sale)
print("MSE of Cubic Model = ", metrics.mean_squared_error(y_test_House_Sale, Cubic_model.predict(X_test_House_Sale3)))

Split V

                                 OLS Regression Results
=======================================================================================
Dep. Variable:             TrueTarget   R-squared (uncentered):                   0.950
Model:                            OLS   Adj. R-squared (uncentered):              0.950
Method:                 Least Squares   F-statistic:                              3873.
Date:                Wed, 11 Mar 2020   Prob (F-statistic):                        0.00
Time:                        08:44:45   Log-Likelihood:                         -12373.
No. Observations:                1022   AIC:                                  2.476e+04
Df Residuals:                    1017   BIC:                                  2.478e+04
Df Model:                           5
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
LotArea         0.2261      0.199      1.135      0.257      -0.165       0.617
TotalBsmtSF    37.7223      3.594     10.495      0.000      30.669      44.775
GarageCars    2.63e+04   2192.254     11.996      0.000     2.2e+04    3.06e+04
AGE          -460.6084     40.531    -11.364      0.000    -540.142    -381.075
TotalArea      71.0272      3.193     22.247      0.000      64.762      77.292
==============================================================================
Omnibus:                      486.069   Durbin-Watson:                   2.033
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            41809.768
Skew:                          -1.257   Prob(JB):                         0.00
Kurtosis:                      34.233   Cond. No.                     2.05e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.05e+04. This might indicate that there are
strong multicollinearity or other numerical problems.


Accuracy of Model =  95.0106244827028

MSE of Training Model =  1918704279.579647
ASE of Validation Set =  1478672714.0065339

MSE of Quadratic Model =  1185405150.9692116
MSE of Cubic Model =  38707821814.62307

# Modelling Assignmnet Part II: 5-Ford Cross Validation

In [15]:
X_House_Sale = pd.DataFrame(House_Sale.iloc[:,:-1])
y_House_Sale = pd.DataFrame(House_Sale.iloc[:,-1])

In [16]:
# 5-fold Cross validation
Linear_kf = KFold(n_splits = 5,shuffle=False)

In [17]:
# Split Data into 5 sets as 4 sets into training and 1 set into testing
for (train_set, test_set) in Linear_kf.split(X_House_Sale):
    print(train_set, test_set)

[ 292  293  294 ... 1457 1458 1459] [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291]
[   0    1    2 ... 1457 1458 1459] [292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309
 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327
 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345
 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363
 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381
 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399
 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417
 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435
 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453
 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471
 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489
 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507
 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525
 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542 543
 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561
 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579
 580 581 582 583]
[   0    1    2 ... 1457 1458 1459] [584 585 586 587 588 589 590 591 592 593 594 595 596 597 598 599 600 601
 602 603 604 605 606 607 608 609 610 611 612 613 614 615 616 617 618 619
 620 621 622 623 624 625 626 627 628 629 630 631 632 633 634 635 636 637
 638 639 640 641 642 643 644 645 646 647 648 649 650 651 652 653 654 655
 656 657 658 659 660 661 662 663 664 665 666 667 668 669 670 671 672 673
 674 675 676 677 678 679 680 681 682 683 684 685 686 687 688 689 690 691
 692 693 694 695 696 697 698 699 700 701 702 703 704 705 706 707 708 709
 710 711 712 713 714 715 716 717 718 719 720 721 722 723 724 725 726 727
 728 729 730 731 732 733 734 735 736 737 738 739 740 741 742 743 744 745
 746 747 748 749 750 751 752 753 754 755 756 757 758 759 760 761 762 763
 764 765 766 767 768 769 770 771 772 773 774 775 776 777 778 779 780 781
 782 783 784 785 786 787 788 789 790 791 792 793 794 795 796 797 798 799
 800 801 802 803 804 805 806 807 808 809 810 811 812 813 814 815 816 817
 818 819 820 821 822 823 824 825 826 827 828 829 830 831 832 833 834 835
 836 837 838 839 840 841 842 843 844 845 846 847 848 849 850 851 852 853
 854 855 856 857 858 859 860 861 862 863 864 865 866 867 868 869 870 871
 872 873 874 875]
[   0    1    2 ... 1457 1458 1459] [ 876  877  878  879  880  881  882  883  884  885  886  887  888  889
  890  891  892  893  894  895  896  897  898  899  900  901  902  903
  904  905  906  907  908  909  910  911  912  913  914  915  916  917
  918  919  920  921  922  923  924  925  926  927  928  929  930  931
  932  933  934  935  936  937  938  939  940  941  942  943  944  945
  946  947  948  949  950  951  952  953  954  955  956  957  958  959
  960  961  962  963  964  965  966  967  968  969  970  971  972  973
  974  975  976  977  978  979  980  981  982  983  984  985  986  987
  988  989  990  991  992  993  994  995  996  997  998  999 1000 1001
 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015
 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029
 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042 1043
 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056 1057
 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071
 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084 1085
 1086 1087 1088 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098 1099
 1100 1101 1102 1103 1104 1105 1106 1107 1108 1109 1110 1111 1112 1113
 1114 1115 1116 1117 1118 1119 1120 1121 1122 1123 1124 1125 1126 1127
 1128 1129 1130 1131 1132 1133 1134 1135 1136 1137 1138 1139 1140 1141
 1142 1143 1144 1145 1146 1147 1148 1149 1150 1151 1152 1153 1154 1155
 1156 1157 1158 1159 1160 1161 1162 1163 1164 1165 1166 1167]
[   0    1    2 ... 1165 1166 1167] [1168 1169 1170 1171 1172 1173 1174 1175 1176 1177 1178 1179 1180 1181
 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1192 1193 1194 1195
 1196 1197 1198 1199 1200 1201 1202 1203 1204 1205 1206 1207 1208 1209
 1210 1211 1212 1213 1214 1215 1216 1217 1218 1219 1220 1221 1222 1223
 1224 1225 1226 1227 1228 1229 1230 1231 1232 1233 1234 1235 1236 1237
 1238 1239 1240 1241 1242 1243 1244 1245 1246 1247 1248 1249 1250 1251
 1252 1253 1254 1255 1256 1257 1258 1259 1260 1261 1262 1263 1264 1265
 1266 1267 1268 1269 1270 1271 1272 1273 1274 1275 1276 1277 1278 1279
 1280 1281 1282 1283 1284 1285 1286 1287 1288 1289 1290 1291 1292 1293
 1294 1295 1296 1297 1298 1299 1300 1301 1302 1303 1304 1305 1306 1307
 1308 1309 1310 1311 1312 1313 1314 1315 1316 1317 1318 1319 1320 1321
 1322 1323 1324 1325 1326 1327 1328 1329 1330 1331 1332 1333 1334 1335
 1336 1337 1338 1339 1340 1341 1342 1343 1344 1345 1346 1347 1348 1349
 1350 1351 1352 1353 1354 1355 1356 1357 1358 1359 1360 1361 1362 1363
 1364 1365 1366 1367 1368 1369 1370 1371 1372 1373 1374 1375 1376 1377
 1378 1379 1380 1381 1382 1383 1384 1385 1386 1387 1388 1389 1390 1391
 1392 1393 1394 1395 1396 1397 1398 1399 1400 1401 1402 1403 1404 1405
 1406 1407 1408 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418 1419
 1420 1421 1422 1423 1424 1425 1426 1427 1428 1429 1430 1431 1432 1433
 1434 1435 1436 1437 1438 1439 1440 1441 1442 1443 1444 1445 1446 1447
 1448 1449 1450 1451 1452 1453 1454 1455 1456 1457 1458 1459]

In [18]:
#Train and Test data in 80:20 ratio
X_train, X_test, y_train, y_test = train_test_split(X_House_Sale, y_House_Sale, test_size=0.2)

In [19]:
# Build Linear Regression
LinearModel = lm_model.LinearRegression()
LinearModel.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
#Compute MSE for Training Data
MSE_train = cross_val_score(LinearModel, X_train, y_train, cv=5, scoring='neg_mean_squared_error')
print("MSE for Training Data = ", -MSE_train)

MSE for Training Data =  [1717764616.177595 3028280583.978971 1898719949.220005 1842847614.143595
 1680097332.988712]

In [21]:
#Average MSE value of Training Data
print("Average MSE of Training Data = ", -MSE_train.mean())

Average MSE of Training Data =  2033542019.3017757

In [22]:
#Model Performance of Training Data
Rsquare_train = cross_val_score(LinearModel, X_train, y_train, cv=5, scoring='r2') * 100
print("R^2 for Training Data = ", Rsquare_train)

R^2 for Training Data =  [72.8767979  51.64906636 70.04006121 68.95361301 76.67276422]

In [27]:
#Compute MSE for Validation Set
ASE_test = cross_val_score(LinearModel, X_test, y_test, cv=5, scoring='neg_mean_squared_error')
print("ASE for Validation Set = ", -ASE_test)

ASE for Validation Set =  [986270899.927222 690382923.504262 2213190858.045462 1004849684.505162
 706656521.663982]

In [24]:
#Average MSE value of Validation Set
print("Average ASE of Validation Set = ", -ASE_test.mean())

Average ASE of Validation Set =  1120270177.529218

In [25]:
#Model Performance of Validation Set
Rsquare_test = cross_val_score(LinearModel, X_test, y_test, cv=5, scoring='r2') * 100
print("R^2 for Testing Data = ", Rsquare_test)

R^2 for Testing Data =  [81.3209915  86.44093389 77.43077877 81.87174515 78.15202876]

In [ ]:
#print("ASE of Training Model = ", np.sum(np.square(np.subtract(train_House_Sale.iloc[:,-1],Linear_model.predict(X_train_House_Sale))))/len(train_House_Sale.iloc[:,-1]))
#print("ASE of Validation Set = ", np.sum(np.square(np.subtract(test_House_Sale.iloc[:,-1],Linear_model.predict(X_test_House_Sale))))/len(test_House_Sale.iloc[:,-1]))
# MSE and ASE values are same for training or testing data

In [46]:
#MSE_train1 = cross_val_score(LinearModel, y_train, LinearModel.predict(X_train), cv=5, scoring='neg_mean_squared_error')
#print("MSE for Training Data = ", -MSE_train1)
#np.set_printoptions(formatter={'float_kind':'{:f}'.format})

MSE for Training Data =  [1026406955.979148 1009176738.126014 1200677612.855372 958986355.713669
 2310247293.670292]